package com.websystique.springmvc.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Customerdetail generated by hbm2java
 */
@Entity
@Table(name = "customerdetail")
public class CustomerDetail implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private String emailid;
	private String contactno;
	private Set<BookService> bookservices = new HashSet<BookService>(0);

	public CustomerDetail() {
	}

	public CustomerDetail(int id) {
		this.id = id;
	}

	public CustomerDetail(int id, String firstname, String lastname, String emailid, String contactno,
			Set<BookService> bookservices) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.emailid = emailid;
		this.contactno = contactno;
		this.bookservices = bookservices;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "emailid", length = 45)
	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	@Column(name = "contactno", length = 45)
	public String getContactno() {
		return this.contactno;
	}

	public void setContactno(String contactno) {
		this.contactno = contactno;
	}

}
