package com.websystique.springmvc.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deal generated by hbm2java
 */
@Entity
@Table(name = "deal")
public class Deal implements java.io.Serializable {

	private Integer id;
	private String dealtype;
	private String description;
	private String image;
	private Date startdate;
	private Date enddate;
	private Set<ServiceCenter> servicecenters = new HashSet<ServiceCenter>(0);

	public Deal() {
	}

	public Deal(int id) {
		this.id = id;
	}

	public Deal(int id, String dealtype, String description, String image, Date startdate, Date enddate,
			Set<ServiceCenter> servicecenters) {
		this.id = id;
		this.dealtype = dealtype;
		this.description = description;
		this.image = image;
		this.startdate = startdate;
		this.enddate = enddate;
		this.servicecenters = servicecenters;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dealtype", length = 45)
	public String getDealtype() {
		return this.dealtype;
	}

	public void setDealtype(String dealtype) {
		this.dealtype = dealtype;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image", length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", length = 10)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 10)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}
}
