package com.websystique.springmvc.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Manufacture generated by hbm2java
 */
@Entity
@Table(name = "manufacture")
public class ManufacturerType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String logo;
	private Set<VechicleModal> modals = new HashSet<VechicleModal>(0);
	private Set<VechicleType> vechicleTypes;

	public ManufacturerType() {
	}

	public ManufacturerType(int id) {
		this.id = id;
	}

	public ManufacturerType(int id, String name, String logo, Set<VechicleModal> modals) {
		this.id = id;
		this.name = name;
		this.logo = logo;
		this.modals = modals;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "logo", length = 45)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}	

	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "vehicaltype_has_manufacture", joinColumns = {
			@JoinColumn(name = "manufacture_id", nullable = false, updatable = false) },
			inverseJoinColumns = { @JoinColumn(name = "vehicaltype_id",
					nullable = false, updatable = false) })
	public Set<VechicleType> getVechicleTypes() {
		return this.vechicleTypes;
	}

	public void setVechicleTypes(Set<VechicleType> vechicleTypes) {
		this.vechicleTypes = vechicleTypes;
	}
}
