package com.websystique.springmvc.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModalId generated by hbm2java
 */
@Embeddable
public class ModalId implements java.io.Serializable {

	private Integer id;
	private Integer manufactureId;

	public ModalId() {
	}

	public ModalId(Integer id, Integer manufactureId) {
		this.id = id;
		this.manufactureId = manufactureId;
	}

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}



}
