package com.websystique.springmvc.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Servercenterdetails generated by hbm2java
 */
@Entity
@Table(name = "servercenterdetails")
public class Servercenterdetails implements java.io.Serializable {

	private Integer servercenterId;
	private ServiceCenter servicecenter;
	private String image;
	private Boolean status;

	public Servercenterdetails() {
	}

	public Servercenterdetails(ServiceCenter servicecenter) {
		this.servicecenter = servicecenter;
	}

	
	public Servercenterdetails(ServiceCenter servicecenter, String image, Boolean status) {
		this.servicecenter = servicecenter;
		this.image = image;
		this.status = status;
	}

	public void setServicecenter(ServiceCenter servicecenter) {
		this.servicecenter = servicecenter;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getServercenterId() {
		return servercenterId;
	}

	public void setServercenterId(Integer servercenterId) {
		this.servercenterId = servercenterId;
	}

	@Column(name = "image", length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
