package com.websystique.springmvc.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ServiceFeedback generated by hbm2java
 */
@Entity
@Table(name = "service_feedback")
public class ServiceFeedback implements java.io.Serializable {

	private Integer id;
	private String serviceid;
	private Integer rating;
	private String comments;

	public ServiceFeedback() {
	}

	public ServiceFeedback(int id) {
		this.id = id;
	}

	public ServiceFeedback(int id, String serviceid, Integer rating, String comments) {
		this.id = id;
		this.serviceid = serviceid;
		this.rating = rating;
		this.comments = comments;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "serviceid", length = 45)
	public String getServiceid() {
		return this.serviceid;
	}

	public void setServiceid(String serviceid) {
		this.serviceid = serviceid;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Column(name = "comments", length = 45)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
