package com.websystique.springmvc.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Variant generated by hbm2java
 */
@Entity
@Table(name = "variant")
public class VechicleVariant implements java.io.Serializable {

	private Integer id;
	private VechicleModal modal;
	private String name;
	private String description;
	private VechicleModal vechicleModal;
	
	public VechicleVariant() {
	}

	public VechicleVariant(Integer id, VechicleModal modal) {
		this.id = id;
		this.modal = modal;
	}

	public VechicleVariant(Integer id, VechicleModal modal, String name, String description) {
		this.id = id;
		this.modal = modal;
		this.name = name;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "modal_id")
	public VechicleModal getVechicleModal() {
		return vechicleModal;
	}

	public void setVechicleModal(VechicleModal vechicleModal) {
		this.vechicleModal = vechicleModal;
	}
	
	

}
