package org.phstudy.sample.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bookservice generated by hbm2java
 */
@Entity
@Table(name = "bookservice")
public class BookService implements java.io.Serializable {

	private Integer id;
	private String bookingId;
	private String manufactureId;
	private String vechicleType;
	private String model;
	private String variant;
	private String bookingdate;
	private String status;
	private String description;
	private String estdeliveryTime;
	private Set<CustomerDetail> customerdetails = new HashSet<CustomerDetail>(0);
	private Set<ServiceCenter> servicecenters = new HashSet<ServiceCenter>(0);

	public BookService() {
	}

	public BookService(Integer id) {
		this.id = id;
	}

	public BookService(Integer id, String bookingId, String manufactureId, String vechicleType, String model,
			String variant, String bookingdate, String status, String description, String estdeliveryTime,
			Set<CustomerDetail> customerdetails, Set<ServiceCenter> servicecenters) {
		this.id = id;
		this.bookingId = bookingId;
		this.manufactureId = manufactureId;
		this.vechicleType = vechicleType;
		this.model = model;
		this.variant = variant;
		this.bookingdate = bookingdate;
		this.status = status;
		this.description = description;
		this.estdeliveryTime = estdeliveryTime;
		this.customerdetails = customerdetails;
		this.servicecenters = servicecenters;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "bookingId", length = 45)
	public String getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(String bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "vechicleType", length = 45)
	public String getVechicleType() {
		return this.vechicleType;
	}

	public void setVechicleType(String vechicleType) {
		this.vechicleType = vechicleType;
	}

	@Column(name = "model", length = 45)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "variant", length = 45)
	public String getVariant() {
		return this.variant;
	}

	public void setVariant(String variant) {
		this.variant = variant;
	}

	@Column(name = "bookingdate", length = 45)
	public String getBookingdate() {
		return this.bookingdate;
	}

	public void setBookingdate(String bookingdate) {
		this.bookingdate = bookingdate;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "estdeliveryTime", length = 45)
	public String getEstdeliveryTime() {
		return this.estdeliveryTime;
	}

	public void setEstdeliveryTime(String estdeliveryTime) {
		this.estdeliveryTime = estdeliveryTime;
	}
}
