package org.phstudy.sample.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VariantId generated by hbm2java
 */
@Embeddable
public class VariantId implements java.io.Serializable {

	private Integer id;
	private Integer modalId;
	private Integer modalManufactureId;

	public VariantId() {
	}

	public VariantId(Integer id, Integer modalId, Integer modalManufactureId) {
		this.id = id;
		this.modalId = modalId;
		this.modalManufactureId = modalManufactureId;
	}

	@Column(name = "id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "modal_id", nullable = false)
	public Integer getModalId() {
		return this.modalId;
	}

	public void setModalId(Integer modalId) {
		this.modalId = modalId;
	}
}
