package org.phstudy.sample.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Modal generated by hbm2java
 */
@Entity
@Table(name = "modal")
public class VechicleModal implements java.io.Serializable {

	private Integer id;
	private String modalname;
	private String image;
	private ManufacturerType manufacturerType;
	
	public VechicleModal() {
	}

	public VechicleModal(Integer id) {
		this.id = id;
	}

	public VechicleModal(Integer id, String modalname, String image) {
		this.id = id;
		this.modalname = modalname;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "modalname", length = 45)
	public String getModalname() {
		return this.modalname;
	}

	public void setModalname(String modalname) {
		this.modalname = modalname;
	}

	@Column(name = "image", length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "manufacture_id")	
	public ManufacturerType getManufacturerType() {
		return manufacturerType;
	}

	public void setManufacturerType(ManufacturerType manufacturerType) {
		this.manufacturerType = manufacturerType;
	}
	
	
}
