package org.phstudy.sample.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Vehicaltype generated by hbm2java
 */
@Entity
@Table(name = "vehicaltype")
public class VechicleType implements java.io.Serializable {

	private Integer id;
	private String type;
	private String name;
	private String description;
	private Set<ServiceCenter> servicecenters = new HashSet<ServiceCenter>(0);

	public VechicleType() {
	}

	public VechicleType(Integer id) {
		this.id = id;
	}

	public VechicleType(Integer id, String type, String name, String description, Set<ServiceCenter> servicecenters) {
		this.id = id;
		this.type = type;
		this.name = name;
		this.description = description;
		this.servicecenters = servicecenters;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
