package org.phstudy.sample.model;
// Generated Jan 28, 2017 3:06:49 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modal generated by hbm2java
 */
@Entity
@Table(name = "modal")
public class VechicleModal implements java.io.Serializable {

	private Integer id;
	private String modalname;
	private String image;
	private Set<VechicleVariant> variants = new HashSet<VechicleVariant>(0);

	public VechicleModal() {
	}

	public VechicleModal(Integer id) {
		this.id = id;
	}

	public VechicleModal(Integer id, String modalname, String image, Set<VechicleVariant> variants) {
		this.id = id;
		this.modalname = modalname;
		this.image = image;
		this.variants = variants;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}


	@Column(name = "modalname", length = 45)
	public String getModalname() {
		return this.modalname;
	}

	public void setModalname(String modalname) {
		this.modalname = modalname;
	}

	@Column(name = "image", length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
